### ISSUE TITLE
Permit run on linux?

### ISSUE THREAD

**Issue by robhogan** [maxim-lobanov/setup-cocoapods#3]
Cocoapods [supports linux](https://github.com/CocoaPods/CocoaPods/blob/master/CHANGELOG.md#120beta1-2016-10-28), at least in a limited way.

I have a React Native project and I'd like to add a CI step to validate `Podfile.lock` by running `pod install` after `npm ci` and checking that the lockfile doesn't change - theoretically this should work fine on linux, and if so it avoids an expensive macos build.

Is there any particular reason this action is [blocked from running on linux](https://github.com/maxim-lobanov/setup-cocoapods/blob/master/src/setup-cocoapods.ts#L7)? Would you be open to adding support if I worked on a PR?

**Comment by maxim-lobanov** [comment]
Hello @rh389 !
The single reason why I have limited it to macOS, I was not aware that it is possible to run cocoapods on Linux image.
If it works and cover your use-case, I don't mind to add support.
Do we need just extend os condition or any other logic is required for Linux? Please let me know how can I assist you.

**Comment by robhogan** [comment]
Hi Maxim,

I've just tried this out by simply [removing the OS check](https://github.com/rh389/setup-cocoapods/commit/5a93375e35d7cce6a6fb12248690ab95ca1e654c) and everything appears to work just fine on an ubuntu base image (I have one stubborn pod that won't build under linux, but that's a separate issue!).

I guess just widening that guard to allow `process.platform === 'linux'` would be neater, but it doesn't seem that there's anything more required than that.

**Comment by maxim-lobanov** [comment]
Great, will be very appreciate for your PR and contribution!
Also, could you please update `.github/workflows/test.yml` file to add one more test case to `ubuntu-latest`.

**Comment by maxim-lobanov** [comment]
@rh389 , thank you for your contribution!
I have released [v1.1](https://github.com/marketplace/actions/setup-cocoapods?version=v1.1) to GA Marketplace. It should be available as `uses: maxim-lobanov/setup-cocoapods@v1.1`

**Comment by robhogan** [comment]
Perfect, thanks for the super-quick turnaround, and thanks for the package!
