### ISSUE TITLE
getVersionFromPodfile doesn't support pre-release versions

### ISSUE THREAD

**Issue by weakfl** [maxim-lobanov/setup-cocoapods#7]
eg. `COCOAPODS: 1.10.0.rc.1` doesn't work

**Comment by maxim-lobanov** [comment]
Hello @weakfl , I think that fix is pretty easy. We just need to extend this regex: https://github.com/maxim-lobanov/setup-cocoapods/blob/master/src/installer.ts#L9
I will take a look today later

**Comment by maxim-lobanov** [comment]
Hello @weakfl , I have added support for pre-release versions via #8 , and released action `v1.2`
Could you please validate it and report back that everything works as expected? After that, I will update `v1` tag.

You may specify `v1.2` in your pipeline:
```
uses: maxim-lobanov/setup-cocoapods@v1.2
```

**Comment by weakfl** [comment]
Thanks for the swift response @maxim-lobanov, works like a charm 👍

**Comment by maxim-lobanov** [comment]
Great, thank you for confirmation.
I have also updated `v1` tag.
